/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a polkit/PolkitAdaptor -c PolkitAdaptor -i polkit/polkithelper.h -l PolkitHelper policykit/org.qt.policykit.rootwrite.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef POLKITADAPTOR_H
#define POLKITADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "polkit/polkithelper.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.qt.policykit.rootwrite
 */
class PolkitAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.qt.policykit.rootwrite")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.qt.policykit.rootwrite\">\n"
"    <method name=\"write\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"code\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"msg\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"content\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    PolkitAdaptor(PolkitHelper *parent);
    virtual ~PolkitAdaptor();

    inline PolkitHelper *parent() const
    { return static_cast<PolkitHelper *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int write(const QString &path, const QString &content, QString &msg);
Q_SIGNALS: // SIGNALS
};

#endif
