/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a polkit/PolkitAdaptor -c PolkitAdaptor -i polkit/polkithelper.h -l PolkitHelper policykit/org.qt.policykit.rootwrite.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "polkit/PolkitAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PolkitAdaptor
 */

PolkitAdaptor::PolkitAdaptor(PolkitHelper *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PolkitAdaptor::~PolkitAdaptor()
{
    // destructor
}

int PolkitAdaptor::write(const QString &path, const QString &content, QString &msg)
{
    // handle method call org.qt.policykit.rootwrite.write
    return parent()->write(path, content, msg);
}

